on:
  push:
    branches:
      - 'main'
      - 'dev'

name: eslint

jobs:
  pylint:
    runs-on: ubuntu-22.04
    steps:
      - name: clone-branch
        run: |
          git clone -b dev https://github.com/Defirence/javascript.git
          printf "List files and cd into repo dir on runner..."
          cd boiler-plate/node-express-server
          ls -lah
          echo $PWD
      - name: eslint
        run: |
          printf "Running eslint against webserver.js..."
          cd boiler-plate/node-express-server
          sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get install curl -y
          curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get install yarn -y
          yarn --version
          yarn install
          npx eslint webserver.js
          printf "Done running pylint checks, exiting ..."
