name: Lint with JSHint

on:
    push:
        branches:
            - main
            - dev
            - tests
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
                cache: 'yarn'

            - name: Install dependencies
              working-directory: node-express-server
              run: yarn install

            - name: Run JSHint lint
              working-directory: node-express-server
              run: npx jshint webserver.js