name: Run Mocha Tests

on:
    push:
        branches:
            - main
            - dev
            - tests
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
                cache: 'yarn'

            - name: Verify `yarn.lock` exists
              working-directory: javascript/node-express-server
              run: |
                if [ ! -f yarn.lock ]; then
                  echo "Error: yarn.lock file is missing in node-express-server directory"
                  exit 1
                fi

            - name: Install dependencies
              working-directory: javascript/node-express-server
              run: yarn install

            - name: Run Mocha tests
              working-directory: javascript/node-express-server
              run: npx mocha test/webserver.test.js